---
- name: Add velero repo
  kubernetes.core.helm_repository:
    repo_url: "{{ velero_repository_url }}"
    repo_name: "{{ velero_repository_name }}"

- name: Install velero
  kubernetes.core.helm:
    chart_ref: "{{ velero_repository_name }}/{{ velero_chart_name }}"
    release_name: "{{ velero_chart_name }}"
    release_namespace: "{{ velero_namespace }}"
    create_namespace: true
    wait: true
    values: "{{ lookup('template', 'files/velero.yaml') | from_yaml }}"
...
